# Generated by Django 2.0.1 on 2018-01-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180111_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_object', models.FileField(upload_to='static/')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachments',
        ),
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(to='app.Attachment'),
        ),
    ]
