# Generated by Django 2.0.1 on 2018-01-12 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180111_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
