# Generated by Django 2.0.1 on 2018-01-14 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20180112_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='app.Attachment'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='recivers',
        ),
        migrations.AddField(
            model_name='message',
            name='recivers',
            field=models.ForeignKey(blank=True, null=True, on_delete='ignore', to=settings.AUTH_USER_MODEL),
        ),
    ]
