# Generated by Django 2.0.1 on 2018-01-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180114_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_object',
            field=models.FileField(upload_to=''),
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='message',
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ManyToManyField(blank=True, null=True, to='app.Message'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
