# Generated by Django 2.0.1 on 2018-01-18 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20180114_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_object',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='message',
            name='recivers',
        ),
        migrations.AddField(
            model_name='message',
            name='recivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
